services:
  - type: web
    name: hms-django
    env: python
    rootDir: .
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn HMS_Django.wsgi:application"
    plan: free
    envVars:
      - key: DEBUG
        fromDatabase: false
        value: "True"
      - key: SECRET_KEY
        fromDatabase: false
        value: 'django-insecure-zvv-ms(+7c)43n5tw)%_=z=49hd9_jy%u2(qimdn!4yjdo)hu@'


