services:
  - type: web
    name: hms-django
    env: python
    rootDir: .
    plan: free

    buildCommand: "pip install -r requirements.txt"

    startCommand: >
      gunicorn HMS_Django.wsgi:application
      --workers 1
      --timeout 120
      --max-requests 200
      --max-requests-jitter 30

    envVars:
      - key: DEBUG
        value: "True"
      - key: SECRET_KEY
        value: "django-insecure-zvv-ms(+7c)43n5tw)%_=z=49hd9_jy%u2(qimdn!4yjdo)hu@"